import type { Metadata } from 'next';
import { headers } from 'next/headers';
import {
  Geist_Mono,
  Plus_Jakarta_Sans,
  Rubik,
} from 'next/font/google';
import { QueryProvider } from '@/providers/QueryProvider';
import { routing } from '@/i18n/routing';
import './globals.css';

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: '--font-plus-jakarta-sans',
  subsets: ['latin'],
  display: 'swap',
});

const rubik = Rubik({
  variable: '--font-rubik',
  subsets: ['arabic', 'latin'],
  display: 'swap',
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const headersList = await headers();
  const pathname = headersList.get('x-pathname') ?? '';
  const pathLocale = pathname.split('/').filter(Boolean)[0];
  const locale = routing.locales.includes(
    pathLocale as (typeof routing.locales)[number],
  )
    ? pathLocale
    : routing.defaultLocale;
  const dir = locale === 'ar' ? 'rtl' : 'ltr';

  return (
    <html
      data-scroll-behavior="smooth"
      lang={locale}
      dir={dir}
      className={`${plusJakartaSans.variable} ${rubik.variable} ${geistMono.variable}`}
    >
      <body>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
